language:
    - ruby
    - node_js
rvm:
    - 1.9.3

node_js:
    - "0.10"
    - "0.8"

before_script:
    - npm install -g grunt-cli

script: grunt test --verbose --force


# whitelist
branches:
  only:
    - gh-pages
