safe: true
lsi: false
pygments: true
url: http://artslondon.github.com/beta/
exclude: [styles, config.rb, config_live.rb, config_local.rb, config_staging.rb, gruntfile.js, package.json, Gemfile, Gemfile.lock, Guardfile, README.md]


# Run Jekyll using local config: jekyll build -w --config _config_local.yml

