lsi: false
pygments: true
url: http://dcdgag63wc396.cloudfront.net
urlgithub : http://artslondon.github.com/beta/
exclude: [styles, config.rb, Gemfile, Gemfile.lock, Guardfile, README.md]
baseurl: /docs/
